### ISSUE TITLE
Feature Request: Add support for stickers

### ISSUE THREAD

**Issue by bob-jones-cs** [EpicGazel/DiscordFreeEmojis#23] opened 2024-10-26 18:38 UTC
As the title says, it would be awesome if support could be added for stickers as well. Thanks for updating the plugin!

**Comment by superfan6000** [comment] 2024-12-13 16:42
there is already a plugin for that

**Comment by EpicGazel** [comment] 2024-12-13 18:05
Duplicate of #6

**Closed by EpicGazel** 2024-12-13 18:05 UTC
